/**
 * ACORN-128 v3 -- a CAESAR portfolio cipher, and the smallest AEAD in this repo.
 *
 * No oracle. What stands behind it is the four vector sets in FELICS's
 * `authenticated_ciphers/source/ciphers/ACORN_1_128_128_293_128_v01/source/test_vectors.c`, and the
 * shape of those fixtures is the point: each one carries **the state after every phase** as well as
 * the ciphertext and tag.
 *
 * That is a materially better fixture than a ciphertext alone, and it earned itself here. The first
 * attempt got all four wrong, and the post-initialisation state matched *exactly* -- which said in one
 * comparison that the step function, the tap positions, the bit order and the 1,792-step key load were
 * all correct and the fault was in a later phase. It was the separator: 256 steps, and I had written
 * 384. A fixture with only ciphertext would have left the whole implementation as the search space.
 *
 * So both intermediate states are asserted here rather than only used for debugging. If a future edit
 * breaks the separator again, the initialisation assertion passing is the message.
 *
 * The four sets between them cover an all-zero key and nonce, a patterned key, associated data at
 * exactly one block and at seven bytes, and messages of 4, 16 and 17 bytes -- so both the byte-aligned
 * and the short cases of each phase are reached. Two of the four are commented out in the source file
 * (FELICS keeps one live at a time via `#if TEST`), which is why they are extracted rather than read
 * off the active arm.
 *
 * **The table below was generated by script from that file, not transcribed.** Hand-copying it went
 * wrong on the first attempt -- `71e8` written as `718e` in one tag, which is a plausible-looking value
 * that fails one assertion and tells you nothing. Same rule as every other fixture here.
 */
import { describe, expect, it } from "vitest";
import { acornDecrypt, acornEncrypt, acornPhaseStates } from "@ocs/algos";

const unhex = (text: string): Uint8Array =>
  text === "" ? new Uint8Array(0) : Uint8Array.from(text.match(/../g)!.map((p) => parseInt(p, 16)));
const hex = (bytes: Uint8Array): string =>
  [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");

interface AcornVector {
  readonly name: string;
  readonly key: string;
  readonly nonce: string;
  readonly ad: string;
  readonly plaintext: string;
  readonly ciphertext: string;
  readonly tag: string;
  /** The 293-bit state packed into 37 bytes, least significant bit first. */
  readonly afterInit: string;
  readonly afterAd: string;
}

const VECTORS: readonly AcornVector[] = [
  {
    name: "input set 1 -- an all-zero key, nonce, associated data and message",
    key: "00000000000000000000000000000000",
    nonce: "00000000000000000000000000000000",
    ad: "00000000000000000000000000000000",
    plaintext: "00000000000000000000000000000000",
    ciphertext: "2b584c510628f8b40218105ab57ff350",
    tag: "e54895692809bf730fee58de8bb0243a",
    afterInit: "7bc64fef9d53425ed0a23a4a20c48bc782f6c4b8b96b3a6714a29e16a251b33aaad0f2761f",
    afterAd: "932f60b8f31a05c9c32d17257722482d8a22d2c32e25f6d264a5abde57ed41defdb9d16116",
  },
  {
    name: "input set 3 -- a patterned key over a full block each way",
    key: "00112233445566778899aabbccddeeff",
    nonce: "00000000000000000000000000000000",
    ad: "ffffffffffffffffffffffffffffffff",
    plaintext: "0123456789abcdef0123456789abcdef",
    ciphertext: "6330b9055103d3ef4e37052dd818403d",
    tag: "758896df0ec539cfb6ebb6dfff2113dd",
    afterInit: "c4075973ab409b9a939e8fe7a3cf476f865a7b7f233a7a84227e0d2179a79ddadc9aee4e03",
    afterAd: "c944986965fabb08feedfa7441745d637387fa260974432f02428b72ab2f12cc400db44712",
  },
  {
    name: "the default set -- four bytes of associated data and four of message",
    key: "00112233445566778899aabbccddeeff",
    nonce: "00000000000000000000000000000000",
    ad: "ffffffff",
    plaintext: "01234567",
    ciphertext: "0ddae004",
    tag: "dd3213acfb0e5162670271e89735d9a2",
    afterInit: "c4075973ab409b9a939e8fe7a3cf476f865a7b7f233a7a84227e0d2179a79ddadc9aee4e03",
    afterAd: "b0aee645c2648600224f34d31e96ff08d855cc51bc83549dfe54be430d20bc8cfc74bb5c00",
  },
  {
    name: "the padding set -- seven bytes of associated data and seventeen of message",
    key: "00112233445566778899aabbccddeeff",
    nonce: "00000000000000000000000000000000",
    ad: "07060504030201",
    plaintext: "11100f0e0d0c0b0a090807060504030201",
    ciphertext: "7aa25ab761456246a1426f055c7dd9fa2d",
    tag: "3dc4b3753b66824d7b6dac5255d7d876",
    afterInit: "c4075973ab409b9a939e8fe7a3cf476f865a7b7f233a7a84227e0d2179a79ddadc9aee4e03",
    afterAd: "3a9d06153f8ca004b6daf91749d87a6e4500f5a7650a23aa3f0efc22db64037ef1ff22470e",
  },
];

describe("ACORN-128 v3", () => {
  it("reproduces every published ciphertext and tag, in both directions", () => {
    expect(VECTORS).toHaveLength(4);
    for (const v of VECTORS) {
      const sealed = acornEncrypt(
        unhex(v.key),
        unhex(v.nonce),
        unhex(v.plaintext),
        unhex(v.ad),
      );
      expect(hex(sealed.subarray(0, v.plaintext.length / 2)), `${v.name} ciphertext`).toBe(
        v.ciphertext,
      );
      expect(hex(sealed.subarray(v.plaintext.length / 2)), `${v.name} tag`).toBe(v.tag);

      // Against the published ciphertext, not a re-encryption of ours.
      const opened = acornDecrypt(
        unhex(v.key),
        unhex(v.nonce),
        unhex(v.ciphertext + v.tag),
        unhex(v.ad),
      );
      expect(hex(opened), `${v.name} decrypt`).toBe(v.plaintext);
    }
  });

  it("reproduces the state after initialisation and after the associated data", () => {
    /**
     * The assertions that make a failure above diagnosable rather than just red. Initialisation is
     * 1,792 steps of the same function the rest of the cipher uses, so a state that matches here rules
     * out the taps, the bit order and the key load in one line -- which is exactly how the separator
     * bug was found.
     */
    for (const v of VECTORS) {
      const states = acornPhaseStates(unhex(v.key), unhex(v.nonce), unhex(v.ad));
      expect(hex(states.afterInit), `${v.name} after init`).toBe(v.afterInit);
      expect(hex(states.afterAd), `${v.name} after associated data`).toBe(v.afterAd);
    }
  });

  it("separates the two paddings, which differ only in one control bit", () => {
    /**
     * The separator after the associated data runs with `cb = 1` and the one after the message with
     * `cb = 0`. So the same bytes as associated data and as message must give different tags -- and a
     * mode that used one constant for both would accept an attacker moving bytes across that boundary,
     * which no round trip can see.
     */
    const key = unhex("00112233445566778899aabbccddeeff");
    const nonce = new Uint8Array(16);
    const block = new Uint8Array(8).fill(0x5a);
    const asAd = acornEncrypt(key, nonce, new Uint8Array(0), block);
    const asMessage = acornEncrypt(key, nonce, block, new Uint8Array(0));
    expect(hex(asAd)).not.toBe(hex(asMessage.subarray(8)));
  });

  it("refuses a tag that has been touched, byte by byte", () => {
    const key = unhex("00112233445566778899aabbccddeeff");
    const nonce = new Uint8Array(16);
    const message = Uint8Array.from({ length: 40 }, (_, i) => (i * 7 + 3) & 0xff);
    const ad = Uint8Array.from({ length: 5 }, (_, i) => i);
    const sealed = acornEncrypt(key, nonce, message, ad);
    expect(hex(acornDecrypt(key, nonce, sealed, ad))).toBe(hex(message));

    for (let i = 0; i < 16; i++) {
      const damaged = Uint8Array.from(sealed);
      damaged[sealed.length - 16 + i] = damaged[sealed.length - 16 + i]! ^ 1;
      expect(() => acornDecrypt(key, nonce, damaged, ad), `tag byte ${i}`).toThrow(
        /does not match/,
      );
    }
    const otherAd = Uint8Array.from(ad);
    otherAd[0] = otherAd[0]! ^ 1;
    expect(() => acornDecrypt(key, nonce, sealed, otherAd)).toThrow(/does not match/);
  });

  it("refuses a key, nonce or sealed message of the wrong length", () => {
    expect(() => acornEncrypt(new Uint8Array(32), new Uint8Array(16), new Uint8Array(0))).toThrow(
      /exactly 16 bytes/,
    );
    expect(() => acornEncrypt(new Uint8Array(16), new Uint8Array(12), new Uint8Array(0))).toThrow(
      /exactly 16 bytes/,
    );
    expect(() => acornDecrypt(new Uint8Array(16), new Uint8Array(16), new Uint8Array(4))).toThrow(
      /at least 16 bytes/,
    );
  });
});
