/**
 * NORX32-4-1 (NORX v3.0) -- a CAESAR third-round candidate, and the reason this one took two tries to
 * unblock rather than one.
 *
 * The KAT files were found long before the specification was: `norx/norx` carries `kat.h` per parameter
 * set, and 5,216 hex values are useless without knowing what inputs produced them or which of the three
 * incompatible NORX versions did. Both halves are settled now, and it is worth recording which source
 * supplied which:
 *
 *  - **FELICS's reference implementation named the version.** Its `initialize.c` sets `S[i] = i` and
 *    runs two bare rounds before loading the key -- which is v3.0's initialisation and nothing else's.
 *  - **`utils/genkat.c` named the inputs.** Four sequences of the form `(i * m + 123) mod 256`, and the
 *    sweep encrypts the first `i` bytes of two of them for every `i` from 0 to 255.
 *
 * So there are two sets, and they are different kinds of evidence: 256 gapless lengths from the
 * designers, and two lengths from an independent port that additionally publish **the state after each
 * of the four phases**. The second is what would localise a failure; the first is what would find one.
 *
 * Both are generated by script from the source files rather than transcribed.
 */
import { describe, expect, it } from "vitest";
import { norxDecrypt, norxEncrypt, norxPhaseStates } from "@ocs/algos";
import { NORX_FELICS, NORX_KAT, NORX_KAT_SEQUENCES } from "./norx-vectors";

const unhex = (text: string): Uint8Array =>
  text === "" ? new Uint8Array(0) : Uint8Array.from(text.match(/../g)!.map((p) => parseInt(p, 16)));
const hex = (bytes: Uint8Array): string =>
  [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");

/** The KAT's inputs, rebuilt from the published rule rather than stored. */
const sequence = (multiplier: number): Uint8Array =>
  Uint8Array.from({ length: 256 }, (_, i) => (i * multiplier + 123) & 0xff);

describe("NORX32-4-1", () => {
  it("reproduces the designers' KAT at every length from 0 to 255", () => {
    expect(NORX_KAT).toHaveLength(256);
    const message = sequence(NORX_KAT_SEQUENCES.message);
    const ad = sequence(NORX_KAT_SEQUENCES.ad);
    const key = sequence(NORX_KAT_SEQUENCES.key).subarray(0, 16);
    const nonce = sequence(NORX_KAT_SEQUENCES.nonce).subarray(0, 16);

    // Collected rather than asserted per row, so a systematic fault reports its whole shape at once.
    const wrong: number[] = [];
    for (let i = 0; i < 256; i++) {
      const sealed = norxEncrypt(key, nonce, message.subarray(0, i), ad.subarray(0, i));
      if (hex(sealed) !== NORX_KAT[i]) wrong.push(i);
    }
    expect(wrong).toEqual([]);
  });

  it("decrypts every KAT row back, against the published ciphertext", () => {
    /**
     * Not a round trip: the input here is the *published* sealed output, so this checks the decrypt
     * path against something other than our own encrypt. It matters more than usual for NORX, because
     * the short final block is genuinely asymmetric -- decryption has to recover the keystream and
     * re-apply the padding marks rather than mirroring the forward path.
     */
    const message = sequence(NORX_KAT_SEQUENCES.message);
    const ad = sequence(NORX_KAT_SEQUENCES.ad);
    const key = sequence(NORX_KAT_SEQUENCES.key).subarray(0, 16);
    const nonce = sequence(NORX_KAT_SEQUENCES.nonce).subarray(0, 16);

    const wrong: number[] = [];
    for (let i = 0; i < 256; i++) {
      const opened = norxDecrypt(key, nonce, unhex(NORX_KAT[i]!), ad.subarray(0, i));
      if (hex(opened) !== hex(message.subarray(0, i))) wrong.push(i);
    }
    expect(wrong).toEqual([]);
  });

  it("covers both block boundaries, which is what 256 gapless rows buy", () => {
    /**
     * The rate is 48 bytes and each row uses the same length for both regions, so lengths 47, 48 and 49
     * exercise "one short block", "exactly one block and no padding block" and "one block plus a padded
     * second" for the associated data and the payload at once. Asserted so that trimming the fixture
     * fails rather than silently narrowing it.
     */
    for (const n of [0, 47, 48, 49, 95, 96, 97]) {
      expect(NORX_KAT[n], `length ${n}`).toBeDefined();
      expect(NORX_KAT[n]!.length / 2, `length ${n} row size`).toBe(n + 16);
    }
  });

  it("reproduces FELICS's two vectors and the state after all four phases", () => {
    expect(NORX_FELICS).toHaveLength(2);
    for (const v of NORX_FELICS) {
      const sealed = norxEncrypt(unhex(v.key), unhex(v.nonce), unhex(v.plaintext), unhex(v.ad));
      expect(hex(sealed), `${v.name} sealed`).toBe(v.ciphertext + v.tag);

      const states = norxPhaseStates(
        unhex(v.key),
        unhex(v.nonce),
        unhex(v.ad),
        unhex(v.plaintext),
      );
      expect(hex(states.afterInit), `${v.name} after init`).toBe(v.afterInit);
      expect(hex(states.afterAd), `${v.name} after associated data`).toBe(v.afterAd);
      expect(hex(states.afterPayload), `${v.name} after payload`).toBe(v.afterPayload);
      expect(hex(states.afterFinal), `${v.name} after finalisation`).toBe(v.afterFinal);
    }
  });

  it("is v3.0, which its initialisation is the marker for", () => {
    /**
     * The three NORX versions are mutually incompatible, and the difference visible earliest is that
     * v3.0 seeds all sixteen words with their own index and runs two bare rounds before the key or the
     * nonce is loaded at all. So the post-initialisation state under a *given* key and nonce is a
     * version fingerprint, and FELICS publishes it -- which is what settled the question that had this
     * algorithm blocked with its vectors already in hand.
     */
    const v = NORX_FELICS[0]!;
    const states = norxPhaseStates(unhex(v.key), unhex(v.nonce), new Uint8Array(0), new Uint8Array(0));
    expect(hex(states.afterInit)).toBe(v.afterInit);
  });

  it("skips an empty region entirely rather than padding it", () => {
    /**
     * Every other sponge in this repo pads an empty header or payload into one block. NORX does not
     * process it at all -- so an empty associated data must give a different tag from a one-byte one,
     * and, more tellingly, the same tag as no associated data argument. Row 0 of the KAT is what pins
     * the first half of that; this pins the behaviour a reader would most likely "fix".
     */
    const key = new Uint8Array(16).fill(0x11);
    const nonce = new Uint8Array(16).fill(0x22);
    const withNone = norxEncrypt(key, nonce, new Uint8Array(0));
    const withEmpty = norxEncrypt(key, nonce, new Uint8Array(0), new Uint8Array(0));
    const withOne = norxEncrypt(key, nonce, new Uint8Array(0), new Uint8Array(1));
    expect(hex(withEmpty)).toBe(hex(withNone));
    expect(hex(withOne)).not.toBe(hex(withNone));
  });

  it("refuses a tag that has been touched, byte by byte", () => {
    const key = new Uint8Array(16).fill(0x33);
    const nonce = new Uint8Array(16).fill(0x44);
    const message = Uint8Array.from({ length: 100 }, (_, i) => (i * 3 + 1) & 0xff);
    const ad = Uint8Array.from({ length: 50 }, (_, i) => i);
    const sealed = norxEncrypt(key, nonce, message, ad);
    expect(hex(norxDecrypt(key, nonce, sealed, ad))).toBe(hex(message));

    for (let i = 0; i < 16; i++) {
      const damaged = Uint8Array.from(sealed);
      damaged[sealed.length - 16 + i] = damaged[sealed.length - 16 + i]! ^ 1;
      expect(() => norxDecrypt(key, nonce, damaged, ad), `tag byte ${i}`).toThrow(/does not match/);
    }
    const otherAd = Uint8Array.from(ad);
    otherAd[0] = otherAd[0]! ^ 1;
    expect(() => norxDecrypt(key, nonce, sealed, otherAd)).toThrow(/does not match/);
  });

  it("refuses a key, nonce or sealed message of the wrong length", () => {
    expect(() => norxEncrypt(new Uint8Array(32), new Uint8Array(16), new Uint8Array(0))).toThrow(
      /exactly 16 bytes/,
    );
    expect(() => norxEncrypt(new Uint8Array(16), new Uint8Array(12), new Uint8Array(0))).toThrow(
      /exactly 16 bytes/,
    );
    expect(() => norxDecrypt(new Uint8Array(16), new Uint8Array(16), new Uint8Array(4))).toThrow(
      /at least 16 bytes/,
    );
  });
});
