export {
  formatShellCommands,
  buildPipedShellVariants,
  buildFileShellVariants,
  formatByteSize,
  getInlineTextSample,
  describeInputExclusion,
  prefixVariantsComment,
  type CliProviderCommand,
  type CliTool,
  type CommandLayout,
  type CommandShell,
  type InputExclusionInfo,
  type ShellCommand,
  type ShellCommandVariants,
} from "@ocs/contracts/shell";
