import type { ToolSample } from "@ocs/engine";

export const RSA_CERTIFICATE_PEM = `-----BEGIN CERTIFICATE-----
MIIERzCCAy+gAwIBAgIUEFfdhlDSCV1zqlRElBHJiJIuj0cwDQYJKoZIhvcNAQEL
BQAwgYIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQH
DA1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKDBBDaXBoZXIgV29ya2JlbmNoMREwDwYD
VQQLDAhTZWN1cml0eTEYMBYGA1UEAwwPd29ya2JlbmNoLmxvY2FsMB4XDTI2MDky
MTIwMzMxNVoXDTM2MDkxODIwMzMxNVowgYIxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
DApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKDBBD
aXBoZXIgV29ya2JlbmNoMREwDwYDVQQLDAhTZWN1cml0eTEYMBYGA1UEAwwPd29y
a2JlbmNoLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmM0f
nJQvPvEcm8owyb9+tXcdKgUsjm2rcBK9bbr8wIis2mbbQtT6dc3qbTC4n5xIz5E8
506BcbsU5zeWyD2Jlzij74o7teiLL2dakpqYMGZSkeORg7zfiw9pEa4S3D/53z+h
2K04IkZEUW0GLzHiyfjQgqsOeWyetS7Sn5SecURz25ylAHWmLg8CTXEPvYXhI9QM
s5qZ3HPz+nEi/erbBiZMto1LbxksVqs3gsIf5lFMxBeyq1oCn6uU5ByDyovyKhGs
v0VFC0t0YWSYovQ6Al2QY2rFt0fDvtg/eJdjyQFZNCOwSDomAl3CdoosMlKrSbvt
Fc2wVwLS+yohYSK4gwIDAQABo4GyMIGvMB0GA1UdDgQWBBRS49WQt5UkUxbEeeQp
ccqpdojfCDAfBgNVHSMEGDAWgBRS49WQt5UkUxbEeeQpccqpdojfCDAzBgNVHREE
LDAqgg93b3JrYmVuY2gubG9jYWyCESoud29ya2JlbmNoLmxvY2FshwR/AAABMAwG
A1UdEwEB/wQCMAAwCwYDVR0PBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
BgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAK+NkF1+p9hNu2L5jz24J1pGIoa+b
Kgc1qIR6C0bxocdFi1krXmt0u+P4ze1KaKwuBsIxKKsPMwneMnIYTX7SbJwF+WNV
4S8SZ8db75aPCXjTJGxitYZckW1FytrNZtXgWfhNWoVgs8iB60tJwHKTTgd2/ljw
djznoQR4KstHyV2OvMg6f0EoYI6V8wTOUDA3pMqjEAJkAL/odWWuDrmMiLE6nql6
VQeAMDIlNPQdef31HBVbGg2i6IWUFFo1XAxihssUAAOy77XzJ8GCs8Smfc5dV7Nk
Icgyaz6QrrGNC6Ctp7w3mw3WxNv5pK3VaNSE/DPVc2ingSUrt4IBRXnDNw==
-----END CERTIFICATE-----`;

export const ECDSA_CSR_PEM = `-----BEGIN CERTIFICATE REQUEST-----
MIIBVTCB+wIBADBbMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEZ
MBcGA1UECgwQQ2lwaGVyIFdvcmtiZW5jaDEcMBoGA1UEAwwTYXBpLndvcmtiZW5j
aC5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLuM5FXrTsh6SieIWr6W
SyysT05sjCBmW2z6Q+bv/DQReLudtVlYnbCJ3onsa0RjDMRe6oF4uLdHyxr1t9Uh
QEqgPjA8BgkqhkiG9w0BCQ4xLzAtMB4GA1UdEQQXMBWCE2FwaS53b3JrYmVuY2gu
bG9jYWwwCwYDVR0PBAQDAgeAMAoGCCqGSM49BAMCA0kAMEYCIQC5wYmRy1VSndGx
K8AykkekOvuyreb7pRRawOqyh2BFQAIhAK0eXQtw2OFUdOg2wrhx9BjtPTmvF1VV
4xAmp97nP56/
-----END CERTIFICATE-----`;

export const CA_CERTIFICATE_PEM = `-----BEGIN CERTIFICATE-----
MIIDfzCCAmegAwIBAgIUGy14/IgV4fk4x9lhwkBn4q4ZVV4wDQYJKoZIhvcNAQEL
BQAwRzELMAkGA1UEBhMCVVMxHDAaBgNVBAoME0NpcGhlciBXb3JrYmVuY2ggQ0Ex
GjAYBgNVBAMMEVdvcmtiZW5jaCBSb290IENBMB4XDTI2MDkyMTIwMzMxOVoXDTM2
MDkxODIwMzMxOVowRzELMAkGA1UEBhMCVVMxHDAaBgNVBAoME0NpcGhlciBXb3Jr
YmVuY2ggQ0ExGjAYBgNVBAMMEVdvcmtiZW5jaCBSb290IENBMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjTYTa357Do1NefL7ywNeZM+FmDmV7Zh8eZE4
gDganBEYNtLLWnqZvc2nQmixIHPV324DWRaHksv8sYnkf/nWsBapjWjJrjBPIGvm
0Y9hQNecVHuLLUfh9L0PeEFr4UABemQFW3fHFoWaepGbpcYQ0xeqqMitHMnvuIB+
GyEw6EifLaAk19PTIFi7H34r0Of9Od4w0PNY+Bw4eFBg72HnbBZ+NfJU6XLReE7q
qA6xhu2ecqfpd+yLtnmEBl8ZbHGbrcVBm9od5lVnNGWe+RVukhzOuwPYAY5LIfUx
+2trsCBQc8mePilYUBwyJ6cix1K6t35WndRmFpRkCnW9ONq7awIDAQABo2MwYTAd
BgNVHQ4EFgQUwX6iZPAFT+mPPnEubg1h97KUdf0wHwYDVR0jBBgwFoAUwX6iZPAF
T+mPPnEubg1h97KUdf0wEgYDVR0TAQH/BAgwBgEB/wIBATALBgNVHQ8EBAMCAQYw
DQYJKoZIhvcNAQELBQADggEBAF9bf6nleeHld3q6jy9dOOKYYktj5dJEAENFb4CX
hYTtDmDuxQIyY+uG7DiSx+V/RLLK8p8FMIArwvpr5ER4WTvD9+IrOc/LZmn5g/6A
HUbWz+CFZ80p7n+Yo9LjrHLJbQ+m8rFPJD/KbIzQkbpF93750DJm1GRQR5+wEwxt
x3VuEqqAkeoiXQMSCXrYPRURm05yIJH73XBybruMKe/hHtPpXA/voYullEGDQH0s
+3sL4dq9OBu5mXPJdhcmL9ghvtjrk1Mt3blw3ZDf/tpel38JTIPE36MSrheanXH4
8eoAD34EJH8GeWmfjKeF/QHsILulycerco40XAlg05cGnrs=
-----END CERTIFICATE-----`;

export const CERTIFICATE_CHAIN_PEM = `${RSA_CERTIFICATE_PEM}\n\n${CA_CERTIFICATE_PEM}`;

export const SAMPLE_ROOT_CA_PEM = `-----BEGIN CERTIFICATE-----
MIIEGDCCAwCgAwIBAgIQYwpzO0249UOv73J1kkHCajANBgkqhkiG9w0BAQsFADCB
hDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNh
biBGcmFuY2lzY28xGTAXBgNVBAoMEENpcGhlciBXb3JrYmVuY2gxETAPBgNVBAsM
CFNlY3VyaXR5MRowGAYDVQQDDBFXb3JrYmVuY2ggUm9vdCBDQTAgFw0yNjA5MjIx
OTMzNTBaGA8yMDU2MDkxNDE5Mzg1MFowgYQxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
DApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKDBBD
aXBoZXIgV29ya2JlbmNoMREwDwYDVQQLDAhTZWN1cml0eTEaMBgGA1UEAwwRV29y
a2JlbmNoIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDO
6QtMtnnYMOEcTDFdXIitbmAEKnnhdkMxo2Fkx6lYSRbtGjdkyxCLGx9ePtEjxWpU
/4FiMnbFxNY8ivhenigFzgpsSeX7xC2GKnhwbupRnq82aJ/nsgVlWYBHXTxfgNU3
mzaHpMftEp/wHy5S1Ygxt5M0yAlR5/O+K/Y7dZQYHsR+X2fGCyBh9B5xJiE1A+b7
xRkE6lG200P8Va9cZmE83FWkJ/XLt1ZC8Xq9MhBTxJokIoQKqYb1g48wefqWmqQD
mzV3xctGV62QqT3L+XV5s7HGLVtJlFRLrmuwLwXSPqAlP8xa27wUpl+NW4vJgI96
/lxW5yJUv2azZuHwp2ddAgMBAAGjgYEwfzAPBgNVHRMBAf8EBTADAQH/MA4GA1Ud
DwEB/wQEAwIBhjAcBgNVHREEFTATghFXb3JrYmVuY2ggUm9vdCBDQTAdBgNVHQ4E
FgQUsrjUEodx9eeewuZeZRLCje1Dm+EwHwYDVR0jBBgwFoAUsrjUEodx9eeewuZe
ZRLCje1Dm+EwDQYJKoZIhvcNAQELBQADggEBAH6PbJxVjF/YOLFiW+BC/7+wpOAV
VkCiiJVrxa4OrqToyCdbGlpy5knvBJgJV0H8HQEgwAsO298t/rvmteum+1RkGDpL
fGNIT7BARBgEOVK2ajNY+SO1/Alq/wLjqJAvIwKawD3DCuuDRzYqBgF2Cbxn/mUC
ua+mAWRwrFSQeQg1d21+OZFn6o+eT/fgTQGdvng/w2cfHT4OePblv5Clj5ozay/x
2jMhcfY/fQBL6CeY4xuKyuVR949k7nGqq2ZdVA0Pv/CDtdim9iQWLKwqtQP134u4
eACsbiO3z1olLiypbePso4TBSv1brK7YtVHjxBxI//iy7EdFookxXgZjmRg=
-----END CERTIFICATE-----`;

export const SAMPLE_2TIER_SERVER_PEM = `-----BEGIN CERTIFICATE-----
MIIEKDCCAxCgAwIBAgIQHDU/+ip09DnECnxf3US5OzANBgkqhkiG9w0BAQsFADCB
hDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNh
biBGcmFuY2lzY28xGTAXBgNVBAoMEENpcGhlciBXb3JrYmVuY2gxETAPBgNVBAsM
CFNlY3VyaXR5MRowGAYDVQQDDBFXb3JrYmVuY2ggUm9vdCBDQTAeFw0yNjA5MjIx
OTMzNTFaFw0zNjA5MTkxOTM4NTFaMIGCMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
Q2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzEZMBcGA1UECgwQQ2lw
aGVyIFdvcmtiZW5jaDERMA8GA1UECwwIU2VjdXJpdHkxGDAWBgNVBAMMD3dvcmti
ZW5jaC5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALNLpW6k
KPv8s2c6SkkmauyjDg+sbvi/NufaSyudFHTiOqKDPB53E7PCBUGyP+7HlNRixDEx
UPHgNTMqsaIz1w+/N/dqAB3ncTMSHXUxLwDs1FGj5IBHNkaeEtf5ZdQCc/8f6wcM
BDB4HJpPgSh9AfLLivpi3NymUl6EskDwxt9teqQZHk/lBiLneEHCTQDI9+PBhZqN
wBdYwaBuk0HgDhnP+32084WQzFLADhryYiM+07zg6wsdtoOerXOgQry47EW514or
7rzKNjlNQfBUu38c78aAhu6jk2VcDmYzkP8QnxMxK0RflDZFDsdCnDdB4BW5Zb6G
zijpjFN1Rccm0KkCAwEAAaOBlTCBkjAPBgNVHRMBAQAEBTADAQEAMA4GA1UdDwEB
/wQEAwIDqDATBgNVHSUEDDAKBggrBgEFBQcDATAaBgNVHREEEzARgglsb2NhbGhv
c3SHBH8AAAEwHQYDVR0OBBYEFBTMJ9EznGlRyM/v1QAY/YNRLL4fMB8GA1UdIwQY
MBaAFLK41BKHcfXnnsLmXmUSwo3tQ5vhMA0GCSqGSIb3DQEBCwUAA4IBAQAPNKbX
CmHtHJT4cuImr7jF82vH+j2YkKfSthtQXw7avQSaJerA8eCkJXJwx52mdnxToAqd
mCDt6UDn0eK5ySXjfjcTkYVwKZZnQOV9ZQrgB86z6hgKU8ho+f9OrlFfBZDpIRlQ
RqdXJ7IANONXEW9riT0AdIg9qEw7qO8eGB7rGDmyeAVxZioi3SSg90P9W0IqqEAP
AaxPZEGF3DgrB2/kTN6ZXxM08l2IMD7dyxbjHzwMutIP7F8ejbwPYlY6BoH4f6Im
sLa1mFHGSXwI0iNJmNmDewWgtNFTYgqYy7M67ypVi7g3Z0vVEo8JX0kazcpNAPuz
eatVLWSZznezHtJo
-----END CERTIFICATE-----`;

export const SAMPLE_2TIER_CHAIN_PEM = `${SAMPLE_2TIER_SERVER_PEM}\n${SAMPLE_ROOT_CA_PEM}`;

export const SAMPLE_3TIER_CHAIN_PEM = `-----BEGIN CERTIFICATE-----
MIICqDCCAk+gAwIBAgIQFi5KRuHeq79jvt/ReJ0WdDAKBggqhkjOPQQDAjCBizEL
MAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBG
cmFuY2lzY28xGTAXBgNVBAoMEENpcGhlciBXb3JrYmVuY2gxETAPBgNVBAsMCFNl
Y3VyaXR5MSEwHwYDVQQDDBhFbnRlcnByaXNlIElzc3VpbmcgQ0EgRzEwHhcNMjYw
OTIyMTkzMzUxWhcNMzYwOTE5MTkzODUxWjCBiDELMAkGA1UEBhMCVVMxEzARBgNV
BAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xGTAXBgNVBAoM
EENpcGhlciBXb3JrYmVuY2gxETAPBgNVBAsMCFNlY3VyaXR5MR4wHAYDVQQDDBVz
ZWN1cmUuaW50ZXJuYWwudmF1bHQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT6
ksUQZV6ex7dooWEIRP4rhJNPVUjE/soZdcVKUbjtj1g2LdZG/kzlqk8jZVOvUgKe
CB7T7rfzKgHjV1CjTn1ao4GVMIGSMA8GA1UdEwEBAAQFMAMBAQAwDgYDVR0PAQH/
BAQDAgOoMBMGA1UdJQQMMAoGCCsGAQUFBwMBMBoGA1UdEQQTMBGCCWxvY2FsaG9z
dIcEfwAAATAdBgNVHQ4EFgQURI2L/sy0GWaIxD5NHrSUqADIgmEwHwYDVR0jBBgw
FoAUDGc/jC2HcDxLKgH2slMoEIPYAGYwCgYIKoZIzj0EAwIDRwAwRAIgL4lhz2Hw
Zq6Ow8TqbZP6Ho5vuMR747wT1SEPIqYPm+kCIFruPaA/IH0B3vr6kshySkJxdYIX
5aqu1GHeWhg+HxBj
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIICpTCCAkqgAwIBAgIQLvwzy8d2FFI8spxat4nTWTAKBggqhkjOPQQDAjCBjDEL
MAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBG
cmFuY2lzY28xGTAXBgNVBAoMEENpcGhlciBXb3JrYmVuY2gxETAPBgNVBAsMCFNl
Y3VyaXR5MSIwIAYDVQQDDBlFbnRlcnByaXNlIEdsb2JhbCBSb290IENBMB4XDTI2
MDkyMjE5MzM1MVoXDTQ2MDkxNzE5Mzg1MVowgYsxCzAJBgNVBAYTAlVTMRMwEQYD
VQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMRkwFwYDVQQK
DBBDaXBoZXIgV29ya2JlbmNoMREwDwYDVQQLDAhTZWN1cml0eTEhMB8GA1UEAwwY
RW50ZXJwcmlzZSBJc3N1aW5nIENBIEcxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAEBBBqGlow/NvYjo4+CAFQDWuQhSEirSYAb6Om82jblqFb68y9bv7MMAwa2FkB
KerrUdR4fpN8I9YL4ZDMreCRyKOBjDCBiTASBgNVHRMBAf8ECDAGAQH/AgEAMA4G
A1UdDwEB/wQEAwIBhjAjBgNVHREEHDAaghhFbnRlcnByaXNlIElzc3VpbmcgQ0Eg
RzEwHQYDVR0OBBYEFAxnP4wth3A8SyoB9rJTKBCD2ABmMB8GA1UdIwQYMBaAFB59
xyBNKYXsu+s5KEEmMXU+72zOMAoGCCqGSM49BAMCA0kAMEYCIQCkR187kaHGH3mj
sojmU5y7cU8cOD6qZk++pZWCg6wVCQIhAPZDYu1VU68/4L2av/8crTmYRBHfRgEk
pmJo2/VDd261
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIICpTCCAkugAwIBAgIQat+ZzCDCi8pJpaxSXHyRSjAKBggqhkjOPQQDAjCBjDEL
MAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBG
cmFuY2lzY28xGTAXBgNVBAoMEENpcGhlciBXb3JrYmVuY2gxETAPBgNVBAsMCFNl
Y3VyaXR5MSIwIAYDVQQDDBlFbnRlcnByaXNlIEdsb2JhbCBSb290IENBMCAXDTI2
MDkyMjE5MzM1MVoYDzIwNTYwOTE0MTkzODUxWjCBjDELMAkGA1UEBhMCVVMxEzAR
BgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xGTAXBgNV
BAoMEENpcGhlciBXb3JrYmVuY2gxETAPBgNVBAsMCFNlY3VyaXR5MSIwIAYDVQQD
DBlFbnRlcnByaXNlIEdsb2JhbCBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0D
AQcDQgAEvEiCImQo/mV7v2b3qyX2doUwcwsUptaKDuG/IyP2smH7EZd42gODP/+6
VzG8rKBeQN0xKU6KP/WigmNGDhCy6KOBijCBhzAPBgNVHRMBAf8EBTADAQH/MA4G
A1UdDwEB/wQEAwIBhjAkBgNVHREEHTAbghlFbnRlcnByaXNlIEdsb2JhbCBSb290
IENBMB0GA1UdDgQWBBQefccgTSmF7LvrOShBJjF1Pu9szjAfBgNVHSMEGDAWgBQe
fccgTSmF7LvrOShBJjF1Pu9szjAKBggqhkjOPQQDAgNIADBFAiAcRpuMHIirXHdY
ALWsLd9wsenS3NCf5ndbwya6e7OBPQIhALmuwWcrHC3HGhbGNNqCMtEP7a0QXr4j
DZZGOeaGwCpn
-----END CERTIFICATE-----`;

export const SAMPLE_CRL_PEM = `-----BEGIN X509 CRL-----
MIICKDCCARACAQEwDQYJKoZIhvcNAQELBQAwgYQxCzAJBgNVBAYTAlVTMRMwEQYD
VQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMRkwFwYDVQQK
DBBDaXBoZXIgV29ya2JlbmNoMREwDwYDVQQLDAhTZWN1cml0eTEaMBgGA1UEAwwR
V29ya2JlbmNoIFJvb3QgQ0EXDTI2MDkyMjE5Mzg1MVoXDTI2MTAyMjE5Mzg1MVow
JjAkAgUA3q2+7xcNMjYwOTIyMTkzODUxWjAMMAoGA1UdFQQDCgEBoC8wLTAKBgNV
HRQEAwIBATAfBgNVHSMEGDAWgBSyuNQSh3H1557C5l5lEsKN7UOb4TANBgkqhkiG
9w0BAQsFAAOCAQEAb7LThdf78v6VXrlNC2R6+2lasdG9crHbZ/HY/efnk25SCtBk
r0kDy9Jg8OtCDqZnmZBD61UrhjEEEYmsKaLBYeEkeiBxHhWsVdEXzVed/LrZKZdu
TijK118JbrCJdmBfsQQT7GGpzhnwyVV5qWI2IyEVaBDaS/USgmtceZl0wGY86gSG
X4eHS/6tzQbiUWlN+3qBJ6IsO6/2KymJ6KdZaI6qjfu5uiCSv1OR7M/odkuTVoBE
FQGiZgkaGusWEC1/X3rzxrRSr6/s65t2yWs1SdMobwnirhqbqYtsX2olTGLPOdIW
+zxVbB7Cc1YDMfvwpnTwr1qTAF712k9UOVOrtw==
-----END X509 CRL-----`;

export function samplesFor(toolId: string): ToolSample[] {
  switch (toolId) {
    case "x509":
      return [
        {
          id: "rsa-tls",
          label: "TLS Server Certificate",
          note: "RSA 2048-bit certificate with SANs and key usage",
          text: RSA_CERTIFICATE_PEM,
        },
        {
          id: "root-ca",
          label: "Root Certificate Authority",
          note: "Self-signed CA certificate with BasicConstraints CA:TRUE",
          text: CA_CERTIFICATE_PEM,
        },
      ];
    case "csr":
      return [
        {
          id: "ec-csr",
          label: "ECDSA P-256 CSR",
          note: "PKCS#10 Certificate Signing Request with requested SANs",
          text: ECDSA_CSR_PEM,
        },
      ];
    case "cert-converter":
      return [
        {
          id: "tls-cert",
          label: "TLS Certificate (PEM)",
          note: "Single PEM certificate to convert to DER or extract public key",
          text: RSA_CERTIFICATE_PEM,
        },
        {
          id: "cert-chain",
          label: "Certificate Chain Bundle",
          note: "Multi-certificate bundle to split into individual certificates",
          text: CERTIFICATE_CHAIN_PEM,
        },
        {
          id: "csr-sample",
          label: "CSR (PKCS#10)",
          note: "Certificate signing request to convert",
          text: ECDSA_CSR_PEM,
        },
      ];
    case "crl":
      return [
        {
          id: "crl-sample",
          label: "X.509 v2 CRL (Revocation List)",
          note: "RFC 5280 CRL containing revoked serial numbers and reason codes",
          text: SAMPLE_CRL_PEM,
        },
      ];
    case "cert-verifier":
      return [
        {
          id: "2tier-chain",
          label: "2-Tier Certificate Chain (Server + Root CA)",
          note: "Valid leaf server certificate cryptographically signed by issuing Root CA",
          text: SAMPLE_2TIER_CHAIN_PEM,
        },
        {
          id: "3tier-chain",
          label: "3-Tier Enterprise Chain (Server + Intermediate + Root CA)",
          note: "Enterprise PKI chain with subordinate issuing CA (ECDSA P-256)",
          text: SAMPLE_3TIER_CHAIN_PEM,
        },
        {
          id: "root-ca-anchor",
          label: "Root CA Trust Anchor",
          note: "Self-signed root certificate authority",
          text: SAMPLE_ROOT_CA_PEM,
        },
      ];
    default:
      return [];
  }
}
